### PR TITLE
New App Icon (Proposal)

### PR DESCRIPTION
**Pull request by Rossi1337**
Created a new App icon. I'm not a designer so you can see this as a first proposal.
The source is the logo.svg file in the assets folder. From that i created the ico for Windows and the icons for MacOS.
For Linux icons are currently not supported out of the box by Flutter. 

Open for discussion.
Related to issue #5

### CODE REVIEW

**Comment by WilliamKarolDiCioccio** [comment]
I like you choose a minimalist style and I like that. It conveys a sense of modernity and approachability. So I think we've outlined the style it should have. However the logo also feels a bit redundant (a chat bubble within a chat bubble). I believe we can still refine it. Moreover we need something to make it stand out, an image that represents the focal point of our work, that why I was thinking of an half human (curved natural shapes) half cybernetic (geometric silicon like shapes) brain symbolizing our will to build a seamless and customizable desktop experience that allows human-machine collaboration.

Speaking of the technical aspect, having PNG variants (in dark/light themes) of the logo would be pretty useful for the app UI.

Leaving this open. I'll let you know more soon.

Anyways I invited you as a collaborator as you've been pretty active and interested ;)

**Comment by Rossi1337** [comment]
Yes you comments make sense. Looking forward to see your proposals.

Leaving here some hints how to create this.
I started with a svg created in Inkscape. From that I exported to png in all sizes. Then I used this online tool to create a multi size ico file for windows https://www.icoconverter.com/

For MacOS you can replace the png files directly in the folder "macos/Runner/Assets.xcassets/AppIcon.appiconset/"

**Comment by WilliamKarolDiCioccio** [comment]
I found a cool tool offering a decent free tier to draw and animate SVGs. It is called [SVGator](https://app.svgator.com/) and looks like a good option to me especially because it allows us to animate the logo and that will come in handy for a splash screen and other branding material

**Comment by Rossi1337** [comment]
I will close this one now. We may want to open a Discussion for this topic instead

**Pull request closed without merging**
